import { useEffect, useRef, useState } from 'react';
import { X, ArrowUpRight, Wallet, Landmark, CircleDollarSign } from 'lucide-react';
import { financeSummary, availableBudget, reservedBudget, formatMoney, pounds } from '../game/finance.js';
import { lockPageScroll } from './pageScroll.js';
import './BudgetOverview.css';

export default function BudgetOverview({state,onClose}){
  const summary=financeSummary(state),[filter,setFilter]=useState('all'),closeRef=useRef(null);
  useEffect(()=>{const release=lockPageScroll(document),previous=document.activeElement;closeRef.current?.focus();const escape=e=>{if(e.key==='Escape')onClose();};document.addEventListener('keydown',escape);return()=>{release();document.removeEventListener('keydown',escape);if(previous?.isConnected)previous.focus();};},[onClose]);
  const transferSpent=summary.ledger.filter(e=>e.pool==='transfer'&&e.amount<0).reduce((n,e)=>n-e.amount,0);
  const segments=[['Available transfer funds',availableBudget(state)*1000000,'#80dc9e'],['Pending transfer fees',reservedBudget(state)*1000000,'#537cdb'],['Remaining wage reserve',summary.reserve,'#d9bf72'],['Transfer spending',transferSpent,'#5b9fb5'],['Wages paid',summary.paid,'#b193c8']];
  const total=segments.reduce((n,s)=>n+s[1],0)||1;let offset=0;
  const transactions=summary.ledger.filter(e=>filter==='all'||filter==='funding'?filter==='all'||e.pool==='allocation'||e.amount>0:filter==='payroll'?e.category==='Weekly payroll':e.pool==='transfer');
  const months=new Map();for(const e of summary.ledger)if(e.date&&e.amount<0&&e.pool!=='allocation'){const month=e.date.slice(0,7);months.set(month,(months.get(month)||0)-e.amount);}
  const trend=[...months].sort().slice(-8),max=Math.max(1,...trend.map(([,n])=>n));
  return <div className="finance-backdrop" onClick={onClose}><section className="finance-dialog" role="dialog" aria-modal="true" aria-label="Budget Overview" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Tab'){const nodes=[...e.currentTarget.querySelectorAll('button')],first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}>
    <header><div><span>CLUB FINANCIAL CONTROL</span><h2>Every pound has a purpose<span>.</span></h2><p>Transfer funds, player wages and the story of your season.</p></div><button ref={closeRef} onClick={onClose} aria-label="Close budget overview"><X size={20}/></button></header>
    <div className="finance-content"><div className="finance-metrics"><article><Wallet size={18}/><small>TRANSFER FUNDS</small><strong>{formatMoney(availableBudget(state))}</strong><span>{formatMoney(reservedBudget(state))} held for pending fees</span></article><article><CircleDollarSign size={18}/><small>WEEKLY PAYROLL</small><strong>{pounds(summary.weekly)}</strong><span>{summary.weeks} payroll weeks remaining</span></article><article><Landmark size={18}/><small>WAGE RESERVE</small><strong>{formatMoney(summary.reserve/1000000)}</strong><span>{formatMoney(summary.allocated/1000000)} funded from transfers</span></article></div>
      <div className="finance-chart-row"><section className="finance-allocation"><div className="finance-donut"><svg viewBox="0 0 220 220" role="img" aria-label="Season resources split between transfer funds, wage reserves and spending"><circle cx="110" cy="110" r="87" fill="none" stroke="#263b2c" strokeWidth="15"/>{segments.map(([name,value,color])=>{const length=value/total*546.637,at=offset;offset+=length;return <circle key={name} cx="110" cy="110" r="87" fill="none" stroke={color} strokeWidth="15" strokeDasharray={`${length} ${546.637-length}`} strokeDashoffset={-at} transform="rotate(-90 110 110)"/>;})}</svg><div><small>SEASON RESOURCES</small><strong>{formatMoney(total/1000000)}</strong><span>Funds + spending</span></div></div><div className="finance-legend">{segments.map(([label,n,color])=><div key={label}><i style={{background:color}}/><span>{label}</span><b>{formatMoney(n/1000000)}</b></div>)}</div></section>
        <section className="finance-trend"><span className="finance-eyebrow">SPENDING RHYTHM</span><h3>Where the season goes.</h3><p>Completed fees and weekly payroll. Moving money into a wage reserve is funding, not another expense.</p><div className="finance-bars">{trend.length?trend.map(([month,n])=><div key={month}><b>{formatMoney(n/1000000)}</b><i style={{height:`${Math.max(4,n/max*100)}px`}}/><small>{new Date(month+'-01T12:00:00Z').toLocaleDateString('en-GB',{month:'short'})}</small></div>):<div className="finance-empty-chart">Your first transaction starts the story.</div>}</div><footer><Landmark size={16}/>{formatMoney(summary.boardFunding/1000000)} board-funded wages for the existing squad.</footer></section></div>
      <section className="finance-transactions"><header><div><span className="finance-eyebrow">THE MONEY TRAIL</span><h3>Season transactions</h3></div><nav aria-label="Finance filters">{[['all','All'],['transfers','Transfers'],['payroll','Payroll'],['funding','Funding']].map(([v,l])=><button key={v} onClick={()=>setFilter(v)} className={v===filter?'active':''}>{l}</button>)}</nav></header><div className="finance-ledger">{transactions.map(e=><article key={e.id}><span className={`finance-entry-icon ${e.pool}`}><ArrowUpRight size={16}/></span><div><strong>{e.category}</strong><small>{e.player|| (e.pool==='wages'?'First-team wage budget':'Club operations')} · {e.date?new Date(e.date+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short'}):'Earlier this season'}</small></div><b className={e.amount<0?'outflow':'inflow'}>{e.amount<0?'−':'+'}{pounds(Math.abs(e.amount))}</b></article>)}{!transactions.length&&<p className="finance-empty-chart">No transactions in this view yet.</p>}</div></section>
      <p className="finance-explainer">Existing squad wages are board-funded. New signings and wage increases reserve their remaining-season cost from transfer funds. Payroll is paid every seven career days; rejected negotiations cost nothing. Unspent transfer-funded wages return when a player leaves.</p>
    </div></section></div>;
}
