import { useEffect, useRef, useState } from 'react';
import { ChevronLeft, FileSignature, Check, ShieldCheck, Handshake, Sparkles } from 'lucide-react';
import { allClubs, clubQuality } from '../game/career.js';
import { marketPlayer } from '../game/freeAgents.js';
import { agentTerms, wageLabel, SQUAD_ROLES, renewalWillingness, contractMonths } from '../game/playerLife.js';
import { formatMoney, contractFunding, availableBudget } from '../game/finance.js';
import { lockPageScroll } from './pageScroll.js';
import './PlayerContracts.css';

export default function ContractTalks({state,talkId,playerId,onSubmit,onEnd,onClose,renderBadge}){
  const talk=state.market?.talks.find(t=>t.id===talkId),club=allClubs(state).find(c=>c.id===state.myClubId);
  const found=talk?marketPlayer(state,talk):club.players.find(p=>p.id===playerId);
  const playerSnapshot=useRef(found),talkSnapshot=useRef(talk);
  const p=found||playerSnapshot.current;
  const date=state.currentDate||'2026-08-15',renewal=!talkId;
  const freeAgent=(talk||talkSnapshot.current)?.kind==='free-agent';
  const signatureStage=renewal||freeAgent?1:2;
  const session=talk||state.renewalTalks?.[playerId]||{round:1,demands:agentTerms(p||{ovr:60,age:20},clubQuality(club),date)};
  const demands=session.demands;
  const [offer,setOffer]=useState(()=>({...demands})),[message,setMessage]=useState('The agent has set out their expectations. Build an agreement that works for both sides.'),[thinking,setThinking]=useState(false),[outcome,setOutcome]=useState(null);
  const timer=useRef(null);
  const dialogRef=useRef(null);
  useEffect(()=>{const release=lockPageScroll(document);return()=>{release();clearTimeout(timer.current);};},[]);
  useEffect(()=>{
    const previous=document.activeElement,dialog=dialogRef.current;
    const controls=()=>[...(dialog?.querySelectorAll('button:not([disabled]),input:not([disabled]),a[href]')||[])].filter(e=>e.offsetParent!==null);
    controls()[0]?.focus();
    const trap=e=>{if(e.key!=='Tab')return;const nodes=controls(),first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}};
    dialog?.addEventListener('keydown',trap);return()=>{dialog?.removeEventListener('keydown',trap);if(previous?.isConnected)previous.focus();};
  },[]);
  useEffect(()=>{const close=e=>{if(e.key==='Escape'&&!thinking)onClose();};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close);},[onClose,thinking]);
  const willing=p&&renewal?renewalWillingness(p,clubQuality(club)):{willing:true};
  const blocked=!willing.willing||(renewal&&contractMonths(p,date)>24);
  const funding=p&&contractFunding(state,p,offer.wage,!renewal);
  const submit=()=>{setThinking(true);timer.current=setTimeout(async()=>{const result=await onSubmit({talkId,playerId,...offer});setThinking(false);setMessage(result.message);if(result.status==='counter')setOffer({...result.demands});if(result.status==='accepted'||result.status==='rejected')setOutcome(result.status);},650);};
  if(!p&&!outcome)return <div className="contract-talks-shell" ref={dialogRef} role="dialog" aria-modal="true" aria-label="Contract talks unavailable"><section className="contract-outcome"><h2>These talks are no longer available.</h2><p>The player or agreement has changed. Check Active Talks for the latest status.</p><button className="submit-offer" onClick={onClose}>Return to your career →</button></section></div>;
  return <div className="contract-talks-shell" ref={dialogRef} role="dialog" aria-modal="true" aria-label={renewal?'Contract renewal':'Player contract negotiation'}>
    <header className="transfer-header"><button className="transfer-back" onClick={onClose}><ChevronLeft size={18}/>Back to career</button><div className="transfer-brand"><span>PERSONAL TERMS</span><strong>{renewal?'Secure their future':'The final signature'}</strong></div><div className="transfer-budget"><small>{renewal?'CONTRACT RENEWAL':freeAgent?'FREE AGENT':'AGREED TRANSFER FEE'}</small><strong>{renewal?'Squad Hub':freeAgent?'No fee':formatMoney(talk?.fee||talkSnapshot.current?.fee||0)}</strong></div></header>
    <main className="contract-talks-main"><nav className="signature-steps" aria-label="Signing progress">{(renewal?['Current deal','Personal terms','New contract']:freeAgent?['Free agent','Personal terms','Confirmed signing']:['Club fee agreed','Player chose you','Personal terms','Confirmed signing']).map((label,i)=><div key={label} className={outcome==='accepted'||i<signatureStage?'complete':i===signatureStage?'current':''}><b>{outcome==='accepted'||i<signatureStage?<Check size={13}/>:i+1}</b><span>{label}</span></div>)}</nav>
      {outcome?<section className="contract-outcome"><div>{outcome==='accepted'?<Sparkles size={38}/>:<Handshake size={38}/>}</div><span className="contract-eyebrow">{outcome==='accepted'?'ALL TERMS AGREED':'TALKS ENDED'}</span><h2>{p?.name||talk?.playerName||'Your player'}</h2><p>{message}</p>{outcome==='accepted'&&<section><b>{offer.years} years</b><b>{wageLabel(offer.wage)}</b><b>{SQUAD_ROLES[offer.role]}</b></section>}<button className="submit-offer" onClick={onClose}>Return to your career →</button></section>:<><div className="personal-talk-heading"><span className="contract-eyebrow">{renewal?'KEEP THE STORY GOING':'A NEW CHAPTER'}</span><h1>Make it official<span>.</span></h1><p>{renewal?'Agree a new chapter, with a role and wage that fit their future.':freeAgent?'No club fee. Just a clear role, a fair wage and a new beginning.':'The club fee is only part of the deal. This is the player’s future.'}</p></div><div className="personal-talk-layout"><section className="agent-side"><div className="agent-player"><b>{p.ovr}<small>OVR</small></b><div><span>{p.role} · Age {p.age}</span><h2>{p.name}</h2><small>{renderBadge(club)} {club.name}</small></div></div><div className={`agent-proposal ${thinking?'is-thinking':''}`} key={session.round}><header><span><Handshake size={16}/>PLAYER’S AGENT</span><b>ROUND {session.round||1} / 3</b></header><h3>{thinking?'Considering your proposal…':blocked?'Not ready for a new deal':'A contract with a clear future.'}</h3><p aria-live="polite">{blocked?willing.reason||'Renewal talks open in the final two years.':message}</p><dl><div><dt>Length</dt><dd>{demands.years} years</dd></div><div><dt>Weekly wage</dt><dd>{wageLabel(demands.wage)}</dd></div><div><dt>Squad role</dt><dd>{SQUAD_ROLES[demands.role]}</dd></div></dl></div><p className="contract-safe"><ShieldCheck size={15}/> {renewal?'Only the extra wage above board funding uses your transfer budget.':freeAgent?'No transfer fee. Wage funding is allocated only when the player signs.':'No transfer fee is charged until all terms are accepted.'}</p></section>
      <section className="personal-offer"><header><span className="contract-eyebrow">YOUR PROPOSAL</span><FileSignature size={24}/></header><label>Contract length <b>{offer.years} years</b></label><div className="contract-years">{[1,2,3,4,5].map(y=><button disabled={thinking||blocked} key={y} className={offer.years===y?'active':''} onClick={()=>setOffer({...offer,years:y})}>{y}<small>{y===1?'year':'years'}</small></button>)}</div><label htmlFor="weekly-wage">Weekly wage <small>GBP / WEEK</small></label><div className="wage-input"><span>£</span><input id="weekly-wage" aria-label="Weekly wage" type="number" min="500" max="2000000" step="500" disabled={thinking||blocked} value={offer.wage} onChange={e=>setOffer({...offer,wage:Number(e.target.value)})}/><small>/ wk</small></div><input className="wage-slider" type="range" aria-label="Adjust weekly wage" disabled={thinking||blocked} min={Math.max(500,Math.floor(demands.wage*.5/500)*500)} max={Math.max(demands.wage+10000,demands.wage*1.6)} step="500" value={offer.wage} onChange={e=>setOffer({...offer,wage:Number(e.target.value)})}/><button className="match-agent" disabled={thinking||blocked} onClick={()=>setOffer({...demands})}>Meet the agent’s terms</button><label>Squad role <small>A PROMISE, NOT A LABEL</small></label><div className="contract-roles">{Object.entries(SQUAD_ROLES).map(([v,l])=><button disabled={thinking||blocked} key={v} className={offer.role===v?'active':''} onClick={()=>setOffer({...offer,role:v})}>{l}</button>)}</div><p className="role-promise">Playing time affects happiness. Promise a role you can deliver.</p><button className="submit-offer" disabled={thinking||blocked} onClick={submit}>{thinking?'Agent is considering…':'Submit personal terms →'}</button><button className="negotiation-end" disabled={thinking} onClick={()=>{onEnd(talkId);setOutcome('rejected');setMessage('You ended talks. No transfer fee was charged.');}}>End negotiations</button><div className="contract-funding-preview"><span>WAGE FUNDING · {funding?.weeks||0} WEEKS LEFT</span><strong>£{Math.max(0,funding?.change||0).toLocaleString('en-GB')}</strong><small>Moves from transfer funds into the wage reserve. Unreserved: {formatMoney(availableBudget(state))}.</small></div><footer>Wages are paid weekly from the funded wage reserve.</footer></section></div></>}
    </main>
  </div>;
}
