import { useState } from 'react';
import { Search, Heart, FileSignature, TrendingUp, ShieldCheck, Clock3, ArrowUpRight, ArrowLeftRight, HandCoins } from 'lucide-react';
import { contractMonths, wageLabel, SQUAD_ROLES, playerPentagon, careerRow, daysBetween } from '../game/playerLife.js';
import { POSITION_OPTIONS, matchesPosition } from '../game/playerBrowse.js';
import { formatMoney } from '../game/finance.js';
import { ClubInterest } from './MarketActivity.jsx';
import { allClubs, marketOpen } from '../game/career.js';
import './PlayerContracts.css';

function AbilityPentagon({player}){
  const values=playerPentagon(player),point=(v,i)=>{const a=-Math.PI/2+i*Math.PI*2/5;return [150+Math.cos(a)*v,142+Math.sin(a)*v];};
  const polygon=v=>values.map((_,i)=>point(v,i).join(',')).join(' ');
  return <section className="dossier-ability"><div className="dossier-section"><span>PLAYER DNA</span><small>{player.attributes?'FC26 base attributes':'Estimated ability profile'}</small></div><svg viewBox="0 0 300 280" role="img" aria-label={`${player.name} ability pentagon`}>{[30,60,90].map(v=><polygon key={v} points={polygon(v)} className="ability-grid"/>)}{values.map((_,i)=><line key={i} x1="150" y1="142" x2={point(90,i)[0]} y2={point(90,i)[1]} className="ability-grid"/>)}<polygon points={values.map(([,v],i)=>point(v*.9,i).join(',')).join(' ')} className="ability-fill"/>{values.map(([label,v],i)=>{const [x,y]=point(116,i);return <text key={label} x={x} y={y} textAnchor="middle"><tspan x={x}>{label}</tspan><tspan x={x} dy="17" className="ability-number">{v??'—'}</tspan></text>;})}</svg></section>;
}
export default function SquadHub({state,club,onRenew,onSell,onLoanOut,renderBadge,focusId=null}){
  const [selected,setSelected]=useState(focusId),[query,setQuery]=useState(''),[position,setPosition]=useState('ALL'),[attention,setAttention]=useState(false);
  const date=state.currentDate||'2026-08-15';
  const alert=p=>p.life?.status==='wants-move'||p.life?.status==='concerned'||(contractMonths(p,date)!==null&&contractMonths(p,date)<=12);
  const players=club.players.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())&&matchesPosition(p,position)&&(!attention||alert(p))).sort((a,b)=>b.ovr-a.ovr);
  const p=players.find(p=>p.id===selected)||players[0];
  const months=p&&contractMonths(p,date),recentlySigned=p?.contract?.signedDate&&daysBetween(p.contract.signedDate,date)<180,canRenew=p&&!p.loan&&!recentlySigned&&(months===null||months<=24),life=p?.life;
  const windowOpen=marketOpen(state),saleListed=state.saleListings?.includes(p?.id),loanListed=state.loanListings?.includes(p?.id);
  const rows=p?[...(p.careerSeasons||[]),careerRow(p,club.id,state.season)].sort((a,b)=>b.season-a.season):[];
  const positions=<><option value="ALL">All positions</option>{POSITION_OPTIONS.map(g=><optgroup label={g.label} key={g.label}>{g.options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</optgroup>)}</>;
  return <section className="squad-hub" aria-label="Squad Hub">
    <header className="squad-hub-heading"><div><span className="contract-eyebrow">PEOPLE BEHIND THE PERFORMANCE</span><h2>Squad Hub<span>.</span></h2><p>Know their game. Understand their future.</p></div><div><b>{club.players.filter(alert).length}</b><small>NEED ATTENTION</small></div></header>
    <div className="squad-hub-layout"><aside className="dossier-roster"><label className="dossier-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a player" aria-label="Search Squad Hub"/></label><div className="dossier-filters"><select value={position} onChange={e=>setPosition(e.target.value)} aria-label="Squad Hub position">{positions}</select><button className={attention?'active':''} onClick={()=>setAttention(!attention)}>Attention</button></div><div className="dossier-player-list">{players.map(x=><button key={x.id} onClick={()=>setSelected(x.id)} className={p?.id===x.id?'selected':''}><b>{x.ovr}</b><span><strong>{x.name}</strong><small>{x.role} · Age {x.age} · {SQUAD_ROLES[x.contract?.role]}</small></span><i className={alert(x)?'needs-attention':'settled'} aria-label={alert(x)?'Needs attention':'Settled'}/></button>)}{!players.length&&<p className="dossier-empty">No players match these filters.</p>}</div></aside>
    {p&&<article className="player-dossier" key={p.id}><header className="dossier-hero"><div className="dossier-watermark">{renderBadge(club)}</div><div className="dossier-number">{p.ovr}<small>OVR</small></div><div><span className="contract-eyebrow">{p.role} · {p.secondaryRoles?.join(' / ')||'FIRST TEAM'}</span><h2>{p.name}</h2><p>Age {p.age} {p.sourceProfile?.nation&&`· ${p.sourceProfile.nation}`} · Value {formatMoney(p.value)}{p.sourceProfile?.height&&` · ${p.sourceProfile.height} cm`}{p.sourceProfile?.foot&&` · ${p.sourceProfile.foot} foot`}</p></div></header>
      <div className="dossier-vitals"><div><small>ENERGY</small><b>{p.energy??100}%</b><meter min="0" max="100" value={p.energy??100}/></div><div><small>MATCH SHARPNESS</small><b>{p.condition??100}%</b><meter min="0" max="100" value={p.condition??100}/></div><div><small>SEASON AVERAGE</small><b>{p.ratedMatches?(p.ratingTotal/p.ratedMatches).toFixed(2):'—'}</b><span>{p.ratedMatches||0} appearances</span></div></div>
      <div className="dossier-main-grid"><AbilityPentagon player={p}/><div className="dossier-future"><section className="dossier-mood"><div className="dossier-section"><span><Heart size={14}/> PLAYER MINDSET</span><b className={`mood-tag mood-${life?.status}`}>{life?.status?.replace('-',' ')||'Settled'}</b></div><h3>{life?.reason||'Settled at the club'}</h3><div className="happiness-track"><i style={{width:`${life?.happiness??72}%`}}/></div><footer><span>Happiness {life?.happiness??72}/100</span><span><TrendingUp size={13}/> {life?.ambition==='high'?'High ambition':'Balanced ambition'}</span></footer></section>
        <section className="dossier-contract"><div className="dossier-section"><span><FileSignature size={14}/> CONTRACT</span><small>{p.contract?.source==='futwiz-fc26'?'FUTWIZ FC26':p.contract?.source==='career'?'IN-GAME AGREEMENT':'SIMULATED TERMS'}</small></div><div className="contract-facts"><div><small>CONTRACT ENDS</small><strong>{p.contract?.endDate?new Date(p.contract.endDate+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):'Not in source'}</strong><span>{months===null?'No verified record':months<=0?'Source term has ended':`${months} months remaining`}</span></div><div><small>WEEKLY WAGE</small><strong>{wageLabel(p.contract?.wage)}</strong><span>{SQUAD_ROLES[p.contract?.role]}</span></div></div><div className="dossier-contract-actions"><button onClick={()=>onRenew(p.id)} disabled={!canRenew}><FileSignature size={16}/><span>{p.loan?'On loan':canRenew?'Renew contract':'Contract settled'}</span><ArrowUpRight size={16}/></button><button className="dossier-loan" onClick={()=>onLoanOut(p.id)} disabled={p.loan||!loanListed&&!windowOpen} title={loanListed?'Remove loan listing':windowOpen?'List for loan':'The transfer window is closed'}><ArrowLeftRight size={14}/>{loanListed?'Unlist loan':'Loan'}</button><button className="dossier-sell" onClick={()=>onSell(p.id)} disabled={p.loan||!saleListed&&!windowOpen} title={saleListed?'Remove transfer listing':windowOpen?'List for transfer':'The transfer window is closed'}><HandCoins size={14}/>{saleListed?'Unlist sale':'Sell'}</button></div><p><Clock3 size={12}/>{recentlySigned?'Recently signed: let the agreement settle for six months.':canRenew?'Agent willingness depends on happiness and ambition.':'Renewal talks open in the final two years.'} Wages are paid weekly from the club’s wage reserve.</p>{p.contract?.sourceUrl&&<a href={p.contract.sourceUrl} target="_blank" rel="noreferrer">View source contract & wage ↗</a>}</section></div></div>
      <ClubInterest state={state} playerId={p.id} renderBadge={renderBadge}/>
      <section className="dossier-history"><div className="dossier-section"><span>YOUR CAREER RECORD</span><small><ShieldCheck size={13}/> Simulated matches only</small></div><div className="dossier-history-scroll"><table><thead><tr><th>Season / club</th><th>Apps</th><th>Goals</th><th>Assists</th><th>Avg</th><th>Best</th></tr></thead><tbody>{rows.map((r,i)=><tr key={`${r.season}:${r.clubId}:${i}`}><td><strong>{2025+r.season}/{String(2026+r.season).slice(-2)}</strong><small>{allClubs(state).find(c=>c.id===r.clubId)?.name||r.clubId}</small></td><td>{r.appearances}</td><td>{r.goals}</td><td>{r.assists}</td><td><b>{r.ratedMatches?(r.ratingTotal/r.ratedMatches).toFixed(2):'—'}</b></td><td>{r.best?r.best.toFixed(1):'—'}</td></tr>)}</tbody></table></div></section>
    </article>}</div>
  </section>;
}
