import { ROLE_GROUP } from "./config.js";
import { GUEST_CRESTS } from "./guestAssets.js";
import { FIRST_SEASON_UCL_ROUNDS } from "./firstSeasonFixtures.js";

const LEAGUE_KEYS={PL:"plClubs",LALIGA:"laligaClubs",SERIEA:"serieaClubs",BUNDES:"bundesligaClubs",LIGUE1:"ligue1Clubs",PORTUGAL:"portugalClubs"};
const UCL_SLOTS={PL:4,LALIGA:4,SERIEA:4,BUNDES:4,LIGUE1:4,PORTUGAL:2};
// Fixed first-season qualifiers. Subsequent seasons use the five domestic top fours;
// the remaining places come from this persistent European guest-club world.
// 2026/27 is a fixed, real-world-inspired entry list. Lyon appears in the
// supplied Europa list too, so it is intentionally kept in Europa: that keeps
// the two 36-club league phases mutually exclusive.
const FIRST_SEASON_IDS=["ars","ast","liv","man","mun","lil","par2","rcl","bor","fcb2","rbl","vfb","rom","com","int","nap","atl","fcb","rea","rma","vil","pt-porto","pt-sporting"];
const FIRST_SEASON_GUEST_IDS=["lask","sabah","bru","sla","aek","fey","psv","bod","viking","slovan","fener","gal","sha"];
const GUESTS=[
  ["psv","PSV Eindhoven","Netherlands",79,"#df2537"],
  ["fey","Feyenoord","Netherlands",78,"#e62e36"],["bru","Club Brugge","Belgium",77,"#173d92"],["cel","Celtic","Scotland",76,"#198659"],["ran","Rangers","Scotland",75,"#2570bc"],
  ["sha","Shakhtar Donetsk","Ukraine",77,"#e46b20"],["sal","RB Salzburg","Austria",77,"#d21f3c"],["gal","Galatasaray","Türkiye",78,"#f2a900"],["sla","Slavia Praha","Czechia",75,"#d51b2d"],
  ["oly","Olympiacos","Greece",76,"#d8202d"],["din","GNK Dinamo Zagreb","Croatia",74,"#2461aa"],["ybo","BSC Young Boys","Switzerland",74,"#e8bf1c"],["bod","Bodø/Glimt","Norway",73,"#e8c022"],
  ["ajae","AFC Ajax","Netherlands",78,"#d82332"],["fcs","FC København","Denmark",73,"#204b91"],["lud","Ludogorets","Bulgaria",72,"#1d9c57"],["qar","Qarabağ FK","Azerbaijan",71,"#244c92"],
  ["ararat","FC Ararat-Armenia","Armenia",67,"#cf262d"],["sturm","SK Sturm Graz","Austria",73,"#121212"],["ander","R.S.C. Anderlecht","Belgium",74,"#5b2c83"],["usg","Royale Union Saint-Gilloise","Belgium",73,"#e2b31d"],["levski","PFC Levski Sofia","Bulgaria",69,"#1b5ca8"],["omonoia","Omonoia FC","Cyprus",68,"#18723e"],["sparta","AC Sparta Praha","Czechia",73,"#7b263b"],["plzen","FC Viktoria Plzeň","Czechia",72,"#254b9d"],["ofi","OFI Crete FC","Greece",67,"#1c1c1c"],["ferenc","Ferencvárosi TC","Hungary",71,"#168f49"],["hapoel","Hapoel Be'er Sheva","Israel",68,"#d5232d"],["az","AZ Alkmaar","Netherlands",74,"#d42027"],["nec","NEC Nijmegen","Netherlands",70,"#bd1e2d"],["lillestrom","Lillestrøm SK","Norway",68,"#f2c300"],["jagiell","Jagiellonia Białystok","Poland",69,"#d9232e"],["lech","Lech Poznań","Poland",70,"#1e71b8"],["torreense","S.C.U. Torreense","Portugal",66,"#b4192a"],["celje","NK Celje","Slovenia",68,"#f1c21b"],["besiktas","Beşiktaş J.K.","Türkiye",72,"#191919"],["lask","LASK","Austria",71,"#151515"],["sabah","Sabah FK","Azerbaijan",67,"#e21f32"],["aek","AEK Athens FC","Greece",72,"#f4c21d"],["viking","Viking FK","Norway",69,"#da2a28"],["slovan","ŠK Slovan Bratislava","Slovakia",70,"#53a6db"],["fener","Fenerbahçe SK","Türkiye",75,"#f0c400"],
  // Conference League 2026/27 guest field. Top-five and Portugal entrants
  // use their playable domestic clubs; these are the remaining guest sides.
  ["egnatia","KF Egnatia","Albania",66,"#2e9a45"],["inter-esc","Inter Club d'Escaldes","Andorra",64,"#1c4a7a"],["gent","K.A.A. Gent","Belgium",73,"#2158a6"],["stvv","Sint-Truidense VV","Belgium",69,"#e0bb24"],["borac","FK Borac Banja Luka","Bosnia and Herzegovina",68,"#254a91"],["cska","PFC CSKA Sofia","Bulgaria",70,"#d1242a"],["hajduk","HNK Hajduk Split","Croatia",72,"#1f5aaa"],["pafos","Pafos FC","Cyprus",69,"#2c6ca3"],["jablonec","FK Jablonec","Czechia",68,"#2b8a4b"],["agf","Aarhus GF","Denmark",70,"#e63020"],["midtjylland","FC Midtjylland","Denmark",72,"#cf1c2e"],["nordsjaelland","FC Nordsjælland","Denmark",71,"#e35c26"],["kups","Kuopion Palloseura","Finland",67,"#f0cd20"],["iberia","FC Iberia 1999","Georgia",65,"#c9272d"],["lincoln","Lincoln Red Imps","Gibraltar",66,"#d61d28"],["pana","Panathinaikos FC","Greece",72,"#23854c"],["kairat","FC Kairat","Kazakhstan",69,"#e1bd21"],["riga","Riga FC","Latvia",68,"#0c3455"],["kauno","FK Kauno Žalgiris","Lithuania",66,"#25834a"],["twente","FC Twente","Netherlands",74,"#d72b2e"],["brann","SK Brann","Norway",70,"#d22630"],["craiova","Universitatea Craiova","Romania",68,"#006cb5"],["hearts","Heart of Midlothian","Scotland",71,"#7a1931"],["zvezda","FK Crvena zvezda","Serbia",73,"#d3242b"],["mjallby","Mjällby AIF","Sweden",67,"#f2d225"],["lugano","FC Lugano","Switzerland",72,"#151515"],["thun","FC Thun","Switzerland",68,"#e23628"],["trabzon","Trabzonspor","Türkiye",72,"#71233a"],
];
// Named senior squads replace the old procedurally generated European players.
// They are deliberately kept at 18 players: enough depth for injuries, rotation
// and the transfer market while avoiding a made-up reserve bench.
const REAL_GUEST_SQUADS={
 ben:"Anatoliy Trubin|GK;Samuel Soares|GK;António Silva|CB;Nicolás Otamendi|CB;Tomás Araújo|CB;Samuel Dahl|LB;Alexander Bah|RB;Fredrik Aursnes|CM;Richard Ríos|CM;Enzo Barrenechea|CDM;Heorhiy Sudakov|CAM;Andreas Schjelderup|LW;Gianluca Prestianni|RW;Kerem Aktürkoğlu|LW;Vangelis Pavlidis|ST;Franjo Ivanović|ST;Henrique Araújo|ST;Leandro Barreiro|CM",
 spo:"Rui Silva|GK;João Virgínia|GK;Gonçalo Inácio|CB;Ousmane Diomande|CB;Zeno Debast|CB;Matheus Reis|LB;Iván Fresneda|RB;Morten Hjulmand|CDM;Hidemasa Morita|CM;Daniel Bragança|CM;Pedro Gonçalves|CAM;Geovany Quenda|RW;Geny Catamo|RW;Francisco Trincão|RW;Maxi Araújo|LW;Conrad Harder|ST;Luis Suárez|ST;Fotis Ioannidis|ST",
 por:"Diogo Costa|GK;Cláudio Ramos|GK;Nehuén Pérez|CB;Jan Bednarek|CB;Tiago Djaló|CB;Francisco Moura|LB;Martim Fernandes|RB;Alan Varela|CDM;Gabri Veiga|CM;Rodrigo Mora|CAM;Fábio Vieira|CAM;Pepê|RW;Borja Sainz|LW;William Gomes|LW;Samu Aghehowa|ST;Deniz Gül|ST;Luuk de Jong|ST;Zaidu Sanusi|LB",
 psv:"Matej Kovář|GK;Nick Olij|GK;Ryan Flamingo|CB;Armando Obispo|CB;Adamo Nagalo|CB;Sergiño Dest|RB;Mauro Júnior|LB;Jerdy Schouten|CDM;Joey Veerman|CM;Ismael Saibari|CAM;Guus Til|CAM;Ivan Perišić|LW;Ruben van Bommel|LW;Couhaib Driouech|LW;Ricardo Pepi|ST;Alassane Pléa|ST;Luuk de Jong|ST;Kiliann Sildillia|RB",
 fey:"Timon Wellenreuther|GK;Justin Bijlow|GK;Gernot Trauner|CB;Thomas Beelen|CB;Facundo González|CB;Givairo Read|RB;Quilindschy Hartman|LB;In-beom Hwang|CM;Quinten Timber|CM;Jakub Moder|CM;Calvin Stengs|CAM;Igor Paixão|LW;Anis Hadj Moussa|RW;Leo Sauer|LW;Ayase Ueda|ST;Julián Carranza|ST;Casper Tengstedt|ST;Bart Nieuwkoop|RB",
 bru:"Simon Mignolet|GK;Nordin Jackers|GK;Joel Ordóñez|CB;Brandon Mechele|CB;Jorne Spileers|CB;Kyriani Sabbe|RB;Bjorn Meijer|LB;Ardon Jashari|CM;Raphael Onyedika|CDM;Hans Vanaken|CAM;Hugo Vetlesen|CM;Christos Tzolis|LW;Carlos Forbs|LW;Mamadou Diakhon|RW;Romeo Vermant|ST;Nicolo Tresoldi|ST;Ferran Jutglà|ST;Joaquin Seys|LB",
 cel:"Kasper Schmeichel|GK;Viljami Sinisalo|GK;Cameron Carter-Vickers|CB;Liam Scales|CB;Auston Trusty|CB;Alistair Johnston|RB;Kieran Tierney|LB;Callum McGregor|CDM;Reo Hatate|CM;Arne Engels|CM;Paulo Bernardo|CAM;Daizen Maeda|LW;Jota|LW;Yang Hyun-jun|RW;James Forrest|RW;Adam Idah|ST;Johnny Kenny|ST;Anthony Ralston|RB",
 ran:"Jack Butland|GK;Liam Kelly|GK;John Souttar|CB;Robin Pröpper|CB;Clinton Nsiala|CB;James Tavernier|RB;Jefté|LB;Nicolas Raskin|CDM;Mohamed Diomande|CM;Connor Barron|CM;Lyall Cameron|CAM;Oscar Cortés|LW;Rabbi Matondo|LW;Findlay Curtis|RW;Hamza Igamane|ST;Cyriel Dessers|ST;Danilo|ST;Dujon Sterling|RB",
 sha:"Dmytro Riznyk|GK;Kiril Fesiun|GK;Mykola Matviyenko|CB;Valeriy Bondar|CB;Alaa Ghram|CB;Yukhym Konoplia|RB;Pedro Henrique|LB;Marlon Gomes|CM;Dmytro Kryskiv|CM;Artem Bondarenko|CAM;Georgiy Sudakov|CAM;Kevin|LW;Eguinaldo|LW;Newerton|RW;Oleksandr Zubkov|RW;Kauã Elias|ST;Lassina Traoré|ST;Vinicius Tobias|RB",
 sal:"Alexander Schlager|GK;Janis Blaswich|GK;Samson Baidoo|CB;Kamil Piątkowski|CB;Joane Gadou|CB;Stefan Lainer|RB;Frans Krätzig|LB;Mads Bidstrup|CDM;Lucas Gourna-Douath|CM;Maurits Kjærgaard|CM;Sota Kitano|CAM;Dorgeles Nene|RW;Adam Daghim|RW;Yorbe Vertessen|LW;Karim Konaté|ST;Petar Ratkov|ST;Moussa Kounfolo Yeo|ST;Mamady Diambou|CM",
 gal:"Uğurcan Çakır|GK;Günay Güvenç|GK;Davinson Sánchez|CB;Abdülkerim Bardakcı|CB;Kaan Ayhan|CB;Roland Sallai|RB;Ismail Jakobs|LB;Lucas Torreira|CDM;Mario Lemina|CM;Gabriel Sara|CAM;İlkay Gündoğan|CM;Yunus Akgün|RW;Barış Alper Yılmaz|RW;Leroy Sané|LW;Victor Osimhen|ST;Mauro Icardi|ST;Ahmed Kutucu|ST;Eren Elmalı|LB",
 sla:"Jindřich Staněk|GK;Aleš Mandous|GK;Tomáš Holeš|CB;Igoh Ogbu|CB;David Zima|CB;Jan Bořil|LB;David Douděra|RB;Oscar Dorley|CDM;Christos Zafeiris|CM;David Moses|CM;Lukáš Provod|CAM;Ivan Schranz|RW;Vasil Kušej|LW;Youssoupha Sanyang|LW;Mojmír Chytil|ST;Tomáš Chorý|ST;Daniel Fila|ST;Michal Sadílek|CM",
 oly:"Konstantinos Tzolakis|GK;Alexandros Paschalakis|GK;Panagiotis Retsos|CB;Lorenzo Pirola|CB;David Carmo|CB;Rodinei|RB;Francisco Ortega|LB;Santiago Hezze|CDM;Dani García|CM;Christos Mouzakitis|CM;Chiquinho|CAM;Gelson Martins|RW;Kristoffer Velde|LW;Costas Fortounis|CAM;Ayoub El Kaabi|ST;Roman Yaremchuk|ST;Mehdi Taremi|ST;Costinha|RB",
 din:"Ivan Nevistić|GK;Danijel Zagorac|GK;Kevin Theophile-Catherine|CB;Raúl Torrente|CB;Mauro Perković|CB;Ronaël Pierre-Gabriel|RB;Bruno Goda|LB;Josip Mišić|CDM;Marko Rog|CM;Luka Stojković|CAM;Martin Baturina|CAM;Arber Hoxha|LW;Marko Pjaca|LW;Dario Špikić|RW;Sandro Kulenović|ST;Dion Drena Beljo|ST;Bruno Petković|ST;Bartol Franjić|CM",
 ybo:"Marvin Keller|GK;David von Ballmoos|GK;Loris Benito|CB;Mohamed Camara|CB;Tanguy Zoukrou|CB;Lewin Blum|RB;Jaouen Hadjam|LB;Sandro Lauper|CDM;Filip Ugrinić|CM;Kastriot Imeri|CAM;Christian Fassnacht|CAM;Alan Virginius|LW;Joel Monteiro|LW;Meschack Elia|RW;Cedric Itten|ST;Silvère Ganvoula|ST;Ebrima Colley|ST;Darian Males|CM",
 bod:"Nikita Haikin|GK;Julian Faye Lund|GK;Odin Bjørtuft|CB;Jostein Gundersen|CB;Villads Nielsen|CB;Fredrik Sjøvold|RB;Fredrik André Bjørkan|LB;Patrick Berg|CDM;Sondre Fet|CM;Ulrik Saltnes|CM;Håkon Evjen|CAM;Jens Petter Hauge|LW;Ole Didrik Blomberg|RW;Sondre Sørli|RW;Kasper Høgh|ST;Andreas Helmersen|ST;Mikkel Bro Hansen|ST;Haitam Aleesami|LB",
 ajae:"Remko Pasveer|GK;Vitezslav Jaroš|GK;Josip Šutalo|CB;Youri Baas|CB;Dies Janse|CB;Anton Gaaei|RB;Owen Wijndal|LB;Kenneth Taylor|CM;Davy Klaassen|CM;Kian Fitz-Jim|CM;Steven Berghuis|CAM;Mika Godts|LW;Raúl Moro|LW;Bertrand Traoré|RW;Wout Weghorst|ST;Brian Brobbey|ST;Kasper Dolberg|ST;Lucas Rosa|RB",
 fcs:"Dominik Kotarski|GK;Nathan Trott|GK;Gabriel Pereira|CB;Pantelis Hatzidiakos|CB;Kevin Diks|CB;Rodrigo Huescas|RB;Birger Meling|LB;Thomas Delaney|CDM;Lukas Lerager|CM;Victor Froholdt|CM;Mohamed Elyounoussi|CAM;Elias Achouri|LW;Viktor Claesson|RW;Andreas Cornelius|ST;Jordan Larsson|ST;Robert|ST;Magnus Mattsson|CAM;William Clem|CM",
 lud:"Hendrik Bonmann|GK;Sergio Padt|GK;Olivier Verdon|CB;Dinis Almeida|CB;Edvin Kurtulus|CB;Aslak Fonn Witry|RB;Anton Nedyalkov|LB;Pedro Naressi|CDM;Jakub Piotrowski|CM;Deroy Duarte|CM;Caio Vidal|CAM;Rick|LW;Bernard Tekpetey|RW;Kwadwo Duah|ST;Rwan Seco|ST;Matias Tissera|ST;Son|LB;Emanuel Insua|LB",
 qar:"Mateusz Kochalski|GK;Shahruddin Mahammadaliyev|GK;Bahlul Mustafazada|CB;Kevin Medina|CB;Matheus Silva|CB;Marko Janković|CM;Elvin Cafarquliyev|LB;Tural Bayramov|RB;Julio Romão|CDM;Kady Borges|CAM;Leandro Andrade|CAM;Abdellah Zoubir|LW;Redon Xhixha|RW;Nəriman Axundzadə|RW;Musa Qurbanlı|ST;Juninho|ST;Hamidou Keyta|ST;Yassine Benzia|CAM",
 // Conference League 2026/27 guest clubs. These are named senior squads,
 // not generated position labels. The shared player builder below supplies
 // gameplay ratings while retaining each real player's identity and role.
 egnatia:"Mario Dajsinani|GK;Igor Lani|GK;Mirsad Jonuz|CB;Lorenc Trashi|CB;Artan Jazxhi|CB;Xheison Ameti|LB;Klevis Haxhiaj|RB;Albano Aleksi|CDM;Regi Lushkja|CM;Sergio Felipe|CM;Nazmi Gripshi|CAM;Bakary Nimaga|CM;Melos Bajrami|LW;Arlind Shkreli|RW;Pedro Augusto|RW;Ermal Krasniqi|ST;Victor da Silva|ST;Klevis Dalipi|ST",
 "inter-esc":"Adri Muñoz|GK;Iker Álvarez|GK;Sascha Andreu|CB;Genís Soldevila|CB;Adrià Gallego|CB;Joan Cervós|LB;Marc Caballé|RB;Víctor Bernat|CDM;David Humanes|CM;Moisés San Nicolás|CM;Álex Martínez|CAM;Rafael de la Fuente|LW;Víctor Martínez|RW;Armand de la Torre|RW;Víctor Sánchez|ST;Mauro Rebelo|ST;Nico Ratti|ST;Jordi Rubio|LB",
 gent:"Davy Roef|GK;Daniel Schmidt|GK;Tsuyoshi Watanabe|CB;Jordan Torunarigha|CB;Matisse Samoise|RB;Noah Fadiga|RB;Archie Brown|LB;Sven Kums|CM;Julien De Sart|CDM;Omri Gandelman|CM;Atsuki Ito|CM;Franck Surdez|LW;Max Dean|ST;Andri Guðjohnsen|ST;Hyun-seok Hong|CAM;Tiago Araújo|RW;Andrew Hjulsager|CAM;Pieter Gerkens|CM",
 stvv:"Leo Kokubo|GK;Tobe Leysen|GK;Bruno Godeau|CB;Shogo Taniguchi|CB;Rein Van Helden|CB;Frederic Ananou|RB;Rihito Yamamoto|LB;Ryoya Ogawa|LB;Mathias Delorge|CM;Joel Chima Fujita|CDM;Ryotaro Ito|CAM;Rocco Reitz|CM;Kahveh Zahiroleslam|ST;Adriano Bertaccini|ST;Andres Ferrari|ST;Robert-Jan Vliegen|RW;Jarne Steuckers|RW;Daichi Hayashi|ST",
 borac:"Nikola Ćetković|GK;Mladen Jurković|GK;Bart Meijers|CB;Jovan Čađo|CB;Maks Juraj Ćelić|CB;Zoran Kvržić|RB;Sebastian Herrera|LB;Srđan Grahovac|CDM;David Čavić|CM;Enver Kulašin|CM;Damir Hrelja|CAM;Sandi Ogrinec|CAM;Stefan Savić|LW;Dino Skorup|RW;Jovo Lukić|ST;Đorđe Despotović|ST;Stojan Vranješ|ST;Aleksandar Subić|LB",
 cska:"Gustavo Busatto|GK;Dimitar Evtimov|GK;Liam Cooper|CB;Thibaut Vion|CB;Lumbardh Dellova|CB;Ivan Turitsov|RB;Mica Pinto|LB;Marcelino Carreazo|CM;James Eto'o|CDM;Ilian Iliev|CM;Stanislav Shopov|CAM;Georgi Chorbadzhiyski|CAM;Michael Estrada|ST;Goduine Koyalipou|ST;Aaron Iseka|ST;Jonathan Lindseth|RW;Ilian Antonov|RW;Sylla|LW",
 hajduk:"Ivan Lučić|GK;Toni Silić|GK;Filip Uremović|CB;Josip Elez|CB;Dominik Prpić|CB;Šimun Hrgović|LB;Niko Sigur|RB;Rokas Pukštas|CM;Filip Krovinović|CM;Ivan Rakitić|CM;Anthony Kalik|CAM;Michele Šego|LW;Bamba|LW;Abdoulie Sanyang|RW;Marko Livaja|ST;Aleksandar Trajkovski|ST;Bruno Durdov|RW;Dario Melnjak|LB",
 pafos:"Ivica Ivušić|GK;Jay Gorter|GK;David Goldar|CB;Derrick Luckassen|CB;Bruno Felipe|CB;João Correia|RB;Jairo|LB;Pêpê|CDM;Muamer Tanković|CAM;Moustapha Name|CM;Vlad Dragomir|CAM;Jajá|LW;Quina|CM;Jairo da Silva|RW;Anderson Silva|ST;Jhonny|ST;Mislav Oršić|LW;Kostas Pileas|LB",
 jablonec:"Jan Hanus|GK;Václav Hanuš|GK;Jakub Martinec|CB;Jan Král|CB;David Štěpánek|CB;Matěj Polidar|LB;Dominik Hollý|RB;Sebastian Nebyla|CM;Michal Beran|CM;David Puškáč|CM;Vachtang Čanturišvili|CAM;Jan Chramosta|ST;Alexis Alégué|RW;Erik Puškáč|LW;Matěj Šín|CAM;Luka Červ|CM;Filip Čihák|CB;David Houska|CM",
 agf:"Jesper Hansen|GK;Leopold Wahlstedt|GK;Frederik Tingager|CB;Jannik Læssøe|CB;Henrik Dalsgaard|CB;Felix Beijmo|RB;Eric Kahl|LB;Nicolai Poulsen|CDM;Mads Emil Madsen|CM;Mikael Anderson|CM;Frederik Brandhof|CM;Janni Serra|ST;Patrick Mortensen|ST;Tobias Bech|LW;Gift Links|LW;Sigurd Haugen|ST;Kristian Arnstad|CAM;Kevin Yakob|CM",
 midtjylland:"Jonas Lössl|GK;Elias Olafsson|GK;Mads Bech Sørensen|CB;Ousmane Diao|CB;Martin Erlić|CB;Joel Andersson|RB;Paulinho|LB;Emiliano Martínez|CDM;Oliver Sørensen|CM;Pedro Bravo|CM;Dani Silva|CAM;Aral Şimşir|LW;Darío Osorio|RW;Valdemar Byskov|CAM;Franculino Djú|ST;Adam Buksa|ST;Cho Gue-sung|ST;Victor Bak Jensen|LB",
 nordsjaelland:"Andreas Hansen|GK;Andreas Søndergaard|GK;Kian Hansen|CB;Lucas Hey|CB;Jeppe Tverskov|CB;Peter Ankersen|RB;Martin Frese|LB;Mads Bidstrup|CM;Mario Dorgeles|CM;Caleb Yirenkyi|CM;Conrad Harder|ST;Sindre Walle Egeli|RW;Andreas Schjelderup|LW;Benjamin Nygren|CAM;Ibrahim Osman|LW;Marcus Ingvartsen|ST;Christian Rasmussen|RW;Tobias Salquist|CB",
 kups:"Johannes Kreidl|GK;Aatu Hakala|GK;Ibrahim Cissé|CB;Paulo Ricardo|CB;Väinö Vehkonen|CB;Saku Savolainen|RB;Janne Saksela|RB;Clinton Antwi|LB;Petteri Pennanen|CM;Anton Popovitch|CM;Jaakko Oksanen|CDM;Oskari Sallinen|CAM;Pyry Lampinen|LW;Otto Ruoppi|RW;Mikael Multanen|ST;Mohamed Touré|ST;Jerry Voutilainen|ST;Arttu Heinonen|CM",
 iberia:"Luka Gugeshashvili|GK;Giorgi Makaridze|GK;Giorgi Rekhviashvili|CB;Saba Goglichidze|CB;Giorgi Tsetskhladze|CB;Levan Kharabadze|LB;Nika Kvekveskiri|RB;Giorgi Kharaishvili|CM;Beka Gviniashvili|CM;Giorgi Papava|CDM;Tornike Morchiladze|CAM;Vakhtang Salia|LW;Otar Mamageishvili|RW;Sandro Altunashvili|CM;Irakli Sikharulidze|ST;Luka Silagadze|ST;Giorgi Guliashvili|ST;Nika Gagnidze|CAM",
 lincoln:"Lee Barron|GK;Dayle Coleing|GK;Bernardo Lopes|CB;Toni Garcia|CB;Jolley|CB;Jack Sergeant|LB;Kian Ronan|RB;Ethan Britto|CM;Liam Walker|CM;Tjay De Barr|CAM;Victor Villacañas|CM;Nano|LW;Kike Gómez|RW;Toni|RW;Juanfri|ST;Mandi|ST;Dylan Borge|ST;Roy Chipolina|CB",
 pana:"Bartłomiej Drągowski|GK;Yuri Lodygin|GK;Tin Jedvaj|CB;Sverrir Ingason|CB;Filip Mladenović|LB;Giannis Kotsiras|RB;Facundo Pellistri|RW;Manolis Siopis|CDM;Nemanja Maksimović|CM;Azzedine Ounahi|CM;Tasos Bakasetas|CAM;Filip Đuričić|CAM;Tete|RW;Daniel Mancini|LW;Fotis Ioannidis|ST;Andraž Šporar|ST;Alexander Jeremejeff|ST;Vitor Hugo|CB",
 kairat:"Aleksandr Zarutskiy|GK;Temirlan Anarbekov|GK;Yegor Sorokin|CB;Aleksandr Martynovich|CB;Alyaksandr Martynovich|CB;Damir Kasabulat|CM;Adilet Sadybekov|CDM;Ofri Arad|CM;Jorginho|CAM;Dastan Satpaev|RW;Giorgi Zaria|CAM;Yerkebulan Seidakhmet|LW;Ricardinho|LW;João Paulo|ST;Élder Santana|ST;Artur Shushenachev|ST;Yan Vorogovskiy|LB;Maksim Zhalmagambetov|RB",
 riga:"Pāvels Šteinbors|GK;Rihards Matrevics|GK;Antonijs Černomordijs|CB;Miloš Ostojić|CB;Hrvoje Babec|CB;Elvis Stuglis|RB;Baba Musah|LB;Rostand Njiki|CDM;Eduards Dašķevičs|CM;Gabriele Gallo|CM;Brian Peña|CAM;Abdoulaye Diallo|LW;Moussa Sanoh|RW;Ibrahim Cissé|RW;Marko Regža|ST;Raimonds Krollis|ST;Dženis Kozica|ST;Roberts Veips|CB",
 kauno:"Deividas Mikelionis|GK;Titas Krapikas|GK;Vilius Armanavičius|CB;Armandas Kučys|CB;Martynas Dapkus|CB;Dovydas Šimkus|RB;Vilius Armalas|LB;Gratas Sirgėdas|CM;Linas Pilibaitis|CM;Fedor Černych|CAM;Rokas Krušnauskas|CAM;Artūras Žulpa|CDM;Olivier Rommens|CM;Amine Benchaib|LW;Temur Chogadze|RW;Mantas Kuklys|ST;Romualdas Jansonas|ST;Karolis Laukžemis|ST",
 twente:"Lars Unnerstall|GK;Przemysław Tytoń|GK;Mees Hilgers|CB;Max Bruns|CB;Alec Van Hoorenbeeck|CB;Bart van Rooij|RB;Gijs Besselink|LB;Michal Sadílek|CM;Carel Eiting|CM;Youri Regeer|CM;Michel Vlap|CAM;Daan Rots|RW;Naci Ünüvar|LW;Sayfallah Ltaief|LW;Ricky van Wolfswinkel|ST;Sam Lammers|ST;Lucas Vennegoor of Hesselink|ST;Anass Salah-Eddine|LB",
 brann:"Mathias Dyngeland|GK;Eirik Holmen Johansen|GK;Japhet Sery Larsen|CB;Thore Pedersen|CB;Fredrik Knudsen|CB;Svenn Crone|RB;Joachim Soltvedt|LB;Felix Horn Myhre|CM;Sivert Heltne Nilsen|CDM;Emil Kornvig|CM;Niklas Castro|CAM;Bård Finne|LW;Mads Sande|RW;Aune Heggebø|ST;Markus Henriksen|ST;Mikkel Andersen|ST;Ulrik Mathisen|CAM;Ole Blomberg|RW",
 craiova:"Silviu Lung Jr.|GK;Laurentiu Popescu|GK;Gregorio Sierra|CB;Raul Silva|CB;Denil Maldonado|CB;Nicușor Bancu|LB;Vladimir Screciu|RB;Alexandru Crețu|CDM;Anzor Mekvabishvili|CM;Lyes Houri|CM;Ștefan Baiaram|LW;Alexandru Mitriță|CAM;Jovan Marković|RW;Andrei Ivan|LW;Elvir Koljić|ST;Basile Mendy|ST;Carlos Mora|RW;Mihai Căpățînă|CM",
 hearts:"Craig Gordon|GK;Zander Clark|GK;Frankie Kent|CB;Stephen Kingsley|CB;Kye Rowles|CB;James Penrice|LB;Michael Smith|RB;Cameron Devlin|CDM;Beni Baningime|CM;Jorge Grant|CM;Lawrence Shankland|ST;Kenneth Vargas|ST;Elton Kabangu|LW;Barrie McKay|LW;Yan Dhanda|CAM;Alan Forrest|RW;Blair Spittal|CAM;Odel Offiah|CB",
 zvezda:"Omri Glazer|GK;Marko Ilić|GK;Uroš Spajić|CB;Miloš Veljković|CB;Nasser Djiga|CB;Young-woo Seol|RB;Milan Rodić|LB;Timi Elsnik|CDM;Rade Krunić|CM;Mirko Ivanić|CAM;Felício Milson|LW;Peter Olayinka|LW;Silas Katompa Mvumpa|RW;Aleksandar Katai|RW;Cherif Ndiaye|ST;Bruno Duarte|ST;Luka Ilić|ST;Maksimović|CAM",
 mjallby:"Noel Törnqvist|GK;Arvid Brorsson|CB;Jacob Bergström|CB;Colin Rösler|CB;Herman Johansson|RB;Gabriel Wallentin|LB;Jesper Löfgren|CDM;Viktor Gustafson|CM;Nicklas Røjkjær|CM;Elliot Stroud|CAM;Abdoulie Manneh|LW;Silas Nwankwo|ST;Alexander Johansson|ST;David Löfquist|CM;Tom Pettersson|CB;Alexander Lundin|GK;Ludvig Malm|RW;Adam Ståhl|RB",
 lugano:"Amir Saipi|GK;Zanotti|GK;Albian Hajdari|CB;Lars Lukas Mai|CB;Ousmane Doumbia|CB;Mattia Zanotti|RB;Martim Marques|LB;Uran Bislimi|CM;Anto Grgic|CM;Yanis Cimignani|CM;Renato Steffen|CAM;Mattia Bottani|CAM;Ignacio Aliseda|LW;Mohamed Belhadj Mahmoud|RW;Shkelqim Vladi|ST;Kacper Przybyłko|ST;Žan Celar|ST;Hicham Mahou|LW",
 thun:"Justin Roth|GK;Andreas Hirzel|GK;Genis Montolio|CB;Basil Stillhart|CB;Nicolas Bürgy|CB;Miguel Castroman|RB;Nils Rüegsegger|LB;Leonard Bertone|CM;Valon Fazliu|CM;Koro Koné|CAM;Dominik Franke|CM;Ashley Barnes|ST;Nino Ziswiler|RW;Jan Bamert|CB;Christopher Ibayi|ST;Liam Chipperfield|LW;Daniel Dos Santos|LW;Marvin Spielmann|RW",
 trabzon:"Uğurcan Çakır|GK;Taha Tepe|GK;Stefan Savić|CB;Arseniy Batagov|CB;Rayyan Baniya|CB;Pedro Malheiro|RB;Mustafa Eskihellaç|LB;Okay Yokuşlu|CDM;Fabinho|CDM|32|80|80|14;Ozan Tufan|CM;Muhammed Cham|CAM;Edin Višća|RW;Oleksandr Zubkov|RW;Mohamed Salah|RW|34|85|85|30;Anthony Nwakaeme|LW;Danylo Sikan|ST;Paul Onuachu|ST;Enis Destan|ST",
};
function seeded(input){let h=2166136261;for(const ch of input){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return (h>>>0)/4294967295;}
function slug(name){return name.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");}
const FALLBACK_ROLES=["GK","GK","CB","CB","CB","LB","RB","CDM","CM","CM","CAM","LW","RW","LW","RW","ST","ST","ST"];
function guestPlayers(id,base){
  const named=(REAL_GUEST_SQUADS[id]||"").split(";").filter(Boolean);
  const rows=named.length?named:FALLBACK_ROLES.map((role,index)=>`${id.replace(/(^|[-_])\\w/g,part=>part.replace("-"," ").toUpperCase())} ${role} ${index+1}|${role}`);
  return rows.map((row,index)=>{const [name,role,ageRaw,ovrRaw,potentialRaw,valueRaw]=row.split("|"),roll=seeded(`${id}:${name}`),generatedAge=18+Math.floor(roll*16),starterBonus=index<2?0:index<11?2:index<15?0:-2,generatedOvr=Math.max(63,Math.min(86,Math.round(base+starterBonus+(roll-.5)*5))),age=Number(ageRaw)||generatedAge,ovr=Number(ovrRaw)||generatedOvr,potential=Math.max(ovr,Number(potentialRaw)||Math.min(91,ovr+(age<21?7:age<24?4:age<28?2:0))),value=Number(valueRaw)||Math.max(1,Math.round((ovr-57)*(ovr-57)*.09));return {id:`eu-${id}-${index}`,slug:slug(name),name,role,group:ROLE_GROUP[role],age,ovr,potential,value,stamina:70+Math.floor(seeded(`${id}:s:${name}`)*20),club:`eu-${id}`,number:index===0?1:index===1?12:index+1,condition:100,energy:100,confidence:0,appearances:0};});
}
export function buildEuropeanGuestClubs(){return GUESTS.map(([id,name,country,base,color])=>({id:`eu-${id}`,name,shortName:name.replace(/^FC |^SL |^AFC |^GNK |^BSC /,""),country,color,crestUrl:GUEST_CRESTS[`eu-${id}`],budget:Math.round((base-65)*4+28),preferredFormation:"4-3-3",leagueAvg:base,guest:true,players:guestPlayers(id,base)}));}
// Existing saves predate part of the European guest world. Preserve their
// player-state changes while ensuring a load also gains every new club.
export function mergedEuropeanGuestClubs(state){
 const savedById=new Map((state?.europeanGuestClubs||[]).map(club=>[club.id,club]));
 return buildEuropeanGuestClubs().map(club=>{const saved=savedById.get(club.id);
  // Upgrade old save files that still contain generated names such as
  // "trabzon CM 9". Named rosters keep normal player-state patches, but the
  // placeholder squads are replaced wholesale on load.
  const stem=club.id.replace(/^eu-/,'').replaceAll('-',' ');
  const hasPlaceholder=(saved?.players||[]).some(player=>new RegExp(`^${stem} (GK|CB|LB|RB|CDM|CM|CAM|LW|RW|ST) \\d+$`,'i').test(player.name||''));
  // Salah and Fabinho were added to Trabzonspor after the first named-roster
  // rollout. Refresh that one legacy squad so existing saves receive them.
  const missingTrabzonMove=club.id==='eu-trabzon'&&!saved?.players?.some(player=>player.name==='Mohamed Salah'||player.name==='Fabinho');
  return saved?{...club,...saved,players:saved.players?.length&&!hasPlaceholder&&!missingTrabzonMove?saved.players:club.players}:club;
 });
}
function strength(club){const best=[...club.players].sort((a,b)=>b.ovr-a.ovr).slice(0,11);return best.reduce((sum,player)=>sum+player.ovr,0)/Math.max(1,best.length);}
function stableShuffle(items,seed){return [...items].sort((a,b)=>seeded(`${seed}:${a.id}`)-seeded(`${seed}:${b.id}`));}
function clubMap(state){return new Map(Object.values(LEAGUE_KEYS).flatMap(key=>state[key]||[]).map(club=>[club.id,club]));}
export function uclQualified(state){return selectUclField(state).some(club=>club.id===state.myClubId);}
export function selectUclField(state){
  const domestic=clubMap(state),guests=mergedEuropeanGuestClubs(state);
  if((state.season||1)===1){const guestById=new Map(guests.map(club=>[club.id.replace(/^eu-/,""),club]));return [...FIRST_SEASON_IDS.map(id=>domestic.get(id)).filter(Boolean),...FIRST_SEASON_GUEST_IDS.map(id=>guestById.get(id)).filter(Boolean)];}
  const qualifiers=Object.entries(LEAGUE_KEYS).flatMap(([league,key])=>{const clubs=state[key]||[];const rows=state.qualificationTables?.[league]||(league===state.league&&state.tableFinal);const ranks=rows?.length?new Map(rows.map((row,index)=>[row.id,index])):null;return [...clubs].sort((a,b)=>ranks?(ranks.get(a.id)??999)-(ranks.get(b.id)??999):strength(b)-strength(a)).slice(0,UCL_SLOTS[league]||4);});
  const europaWinner=state.uel?.championId?[...domestic.values(),...guests].find(club=>club.id===state.uel.championId):null;
  const unique=[...new Map([...qualifiers,europaWinner].filter(Boolean).map(club=>[club.id,club])).values()];
  return [...unique,...stableShuffle(guests,`ucl-${state.season}`).filter(club=>!unique.some(qualifier=>qualifier.id===club.id)).slice(0,36-unique.length)];
}
export function createUclCampaign(state,roundRobin,initTable){const clubs=selectUclField(state),ids=clubs.map(club=>club.id),rounds=state.season===1?FIRST_SEASON_UCL_ROUNDS:roundRobin(ids).slice(0,8);return {stage:"hub",clubs,rounds,roundIndex:0,tableRaw:initTable(ids),form:{},lastMatch:null,campaignResults:[],campaignRecord:{w:0,d:0,l:0,gf:0,ga:0},phaseTable:null,qualification:null,knockoutRounds:[],knockoutRoundIndex:0,knockoutFaced:[],currentKnockoutOpponentId:null,leg:1,aggregate:{mine:0,opp:0},firstLegHomeA:undefined,outcome:null};}
// Repair old saves where the campaign has no persistent European guest-club field.
export function repairUclField(state){
 const guests=mergedEuropeanGuestClubs(state),base={...state,europeanGuestClubs:guests};
 const guestById=new Map(guests.map(club=>[club.id,club]));
 // UEL and UECL may be the active campaign when a save is restored. Refresh
 // their guest references too, so an in-progress Conference save immediately
 // shows the named roster in match screens and the transfer market.
 for(const key of ['uel','uecl'])if(Array.isArray(base[key]?.clubs))base[key]={...base[key],clubs:base[key].clubs.map(club=>guestById.get(club.id)||club),clubIds:base[key].clubs.map(club=>club.id)};
 const u=base.ucl;if(!u||!Array.isArray(u.clubs)||!Array.isArray(u.rounds))return base;
 // A live UCL table/bracket may still hold objects from an earlier save. Replace
 // only its guest references, retaining results and every domestic club exactly.
 const refreshed=u.clubs.map(club=>guestById.get(club.id)||club);
 if(u.phaseTable||u.knockoutBracket)return {...base,ucl:{...u,clubs:refreshed,clubIds:refreshed.map(club=>club.id)}};
 const wanted=selectUclField({...base,ucl:{...u,clubs:refreshed}});
 if(refreshed.length===36&&refreshed.some(club=>club.guest))return {...base,ucl:{...u,clubs:refreshed,clubIds:refreshed.map(club=>club.id)}};
 const protectedIds=new Set([state.myClubId,u.lastMatch?.opponentId,...(u.campaignResults||[]).map(result=>result.opponentId)]);
 const keep=refreshed.filter(club=>protectedIds.has(club.id)),ids=new Set(keep.map(club=>club.id));
 const clubs=[...keep,...wanted.filter(club=>!ids.has(club.id)).slice(0,36-keep.length)];
 return clubs.length===36?{...base,ucl:{...u,clubs,clubIds:clubs.map(club=>club.id)}}:base;
}
